desc = "Nanosecond resolution for times, dates, timezones."
keywords = ["Julia", "nanosecond", "nanoseconds", "time", "datetime", "timezone", "timezones"]
name = "TimesDates"
uuid = "bdfc003b-8df8-5c39-adcd-3a9087f5df4a"
repo = "https://github.com/JeffreySarnoff/TimesDates.jl.git"
author = "Jeffrey Sarnoff <jeffrey.sarnoff@gmail.com>"
license = "MIT"
version = "v0.3.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
CompoundPeriods = "a216cea6-0a8c-5945-ab87-5ade47210022"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[compat]
CompoundPeriods = "^0.5.1, 0.6"
TimeZones = "1"
julia = "^1.6"
