desc = "Nanosecond resolution for times, dates, timezones."
keywords = ["nanosecond", "nanoseconds", "time", "datetime", "timezone", "timezones"]
name = "TimesDates"
uuid = "bdfc003b-8df8-5c39-adcd-3a9087f5df4a"
repo = "https://github.com/JeffreySarnoff/TimesDates.jl.git"
author = "Jeffrey Sarnoff <jeffrey.sarnoff@gmail.com>"
license = "MIT"
version = "v0.2.5"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
CompoundPeriods = "a216cea6-0a8c-5945-ab87-5ade47210022"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1"
CompoundPeriods = "0"
TimeZones = "0"
