const YEARS_PER_GREGORIAN_CYCLE = Int64(400)
const DAYS_PER_GREGORIAN_CYCLE  = Int64(146_097)

const MONTHS_PER_YEAR    = Int64(12)
const DAYS_PER_WEEK      = Int(7)
const WEEKDAYS_PER_WEEK  = Int(5)
const HOURS_PER_DAY      = Int64(24)
const MINUTES_PER_HOUR   = Int64(60)
const SECONDS_PER_MINUTE = Int64(60)
const MILLISECONDS_PER_SECOND      = Int64(1_000)
const MICROSECONDS_PER_MILLISECOND = Int64(1_000)
const NANOSECONDS_PER_MICROSECOND  = Int64(1_000)

const PICOSECONDS_PER_NANOSECOND   = Int128(1_000)
const FEMTOSECONDS_PER_NANOSECOND  = Int128(1_000_000)
const ATTOSECONDS_PER_NANOSECOND   = Int128(1_000_000_000)
const ZEPTOSECONDS_PER_NANOSECOND  = Int128(1_000_000_000_000)
const YOCTOSECONDS_PER_NANOSECOND  = Int128(1_000_000_000_000_000)

const MINUTES_PER_DAY  = MINUTES_PER_HOUR   * HOURS_PER_DAY
const SECONDS_PER_HOUR = SECONDS_PER_MINUTE * MINUTES_PER_HOUR
const SECONDS_PER_DAY  = SECONDS_PER_HOUR   * HOURS_PER_DAY

const MILLISECONDS_PER_MINUTE = MILLISECONDS_PER_SECOND * SECONDS_PER_MINUTE
const MILLISECONDS_PER_HOUR   = MILLISECONDS_PER_MINUTE * MINUTES_PER_HOUR
const MILLISECONDS_PER_DAY    = MILLISECONDS_PER_HOUR   * HOURS_PER_DAY

const MICROSECONDS_PER_SECOND = MICROSECONDS_PER_MILLISECOND * MILLISECONDS_PER_SECOND
const MICROSECONDS_PER_MINUTE = MICROSECONDS_PER_SECOND * SECONDS_PER_MINUTE
const MICROSECONDS_PER_HOUR   = MICROSECONDS_PER_MINUTE * MINUTES_PER_HOUR
const MICROSECONDS_PER_DAY    = MICROSECONDS_PER_HOUR   * HOURS_PER_DAY

const NANOSECONDS_PER_MILLISECOND = NANOSECONDS_PER_MICROSECOND * MICROSECONDS_PER_MILLISECOND
const NANOSECONDS_PER_SECOND = NANOSECONDS_PER_MILLISECOND * MILLISECONDS_PER_SECOND
const NANOSECONDS_PER_MINUTE = NANOSECONDS_PER_SECOND * SECONDS_PER_MINUTE
const NANOSECONDS_PER_HOUR   = NANOSECONDS_PER_MINUTE * MINUTES_PER_HOUR
const NANOSECONDS_PER_DAY    = NANOSECONDS_PER_HOUR   * HOURS_PER_DAY

const PICOSECONDS_PER_SECOND  = PICOSECONDS_PER_NANOSECOND * NANOSECONDS_PER_SECOND
const FEMTOSECONDS_PER_SECOND = FEMTOSECONDS_PER_NANOSECOND * NANOSECONDS_PER_SECOND
const ATTOSECONDS_PER_SECOND  = ATTOSECONDS_PER_NANOSECOND  * NANOSECONDS_PER_SECOND
const ZEPTOSECONDS_PER_SECOND = ZEPTOSECONDS_PER_NANOSECOND * NANOSECONDS_PER_SECOND
const YOCTOSECONDS_PER_SECOND = YOCTOSECONDS_PER_NANOSECOND * NANOSECONDS_PER_SECOND


const MONTHS_PER_GREGORIAN_CYCLE  = YEARS_PER_GREGORIAN_CYCLE   * MONTHS_PER_YEAR
const HOURS_PER_GREGORIAN_CYCLE   = DAYS_PER_GREGORIAN_CYCLE    * HOURS_PER_DAY
const MINUTES_PER_GREGORIAN_CYCLE = HOURS_PER_GREGORIAN_CYCLE   * MINUTES_PER_HOUR
const SECONDS_PER_GREGORIAN_CYCLE = MINUTES_PER_GREGORIAN_CYCLE * SECONDS_PER_MINUTE
const MILLISECONDS_PER_GREGORIAN_CYCLE = SECONDS_PER_GREGORIAN_CYCLE * MILLISECONDS_PER_SECOND
const MICROSECONDS_PER_GREGORIAN_CYCLE = Int128(SECONDS_PER_GREGORIAN_CYCLE) * MICROSECONDS_PER_SECOND
const NANOSECONDS_PER_GREGORIAN_CYCLE  = Int128(SECONDS_PER_GREGORIAN_CYCLE) * NANOSECONDS_PER_SECOND
