

Year(td::TimeDate)   = Year(date(td))
Month(td::TimeDate)  = Month(date(td))
Day(td::TimeDate)    = Day(date(td))
Hour(td::TimeDate)   = Hour(time(td))
Minute(td::TimeDate) = Minute(time(td))
Second(td::TimeDate) = Second(time(td))
Millisecond(td::TimeDate) = Millisecond(time(td))
Microsecond(td::TimeDate) = Microsecond(time(td))
Nanosecond(td::TimeDate)  = Nanosecond(time(td))

Year(tdz::TimeDateZone)   = Year(date(tdz))
Month(tdz::TimeDateZone)  = Month(date(tdz))
Day(tdz::TimeDateZone)    = Day(date(tdz))
Hour(tdz::TimeDateZone)   = Hour(time(tdz))
Minute(tdz::TimeDateZone) = Minute(time(tdz))
Second(tdz::TimeDateZone) = Second(time(tdz))
Millisecond(tdz::TimeDateZone) = Millisecond(time(tdz))
Microsecond(tdz::TimeDateZone) = Microsecond(time(tdz))
Nanosecond(tdz::TimeDateZone)  = Nanosecond(time(tdz))

year(td::TimeDate)   = year(date(td))
month(td::TimeDate)  = month(date(td))
day(td::TimeDate)    = day(date(td))
hour(td::TimeDate)   = hour(time(td))
minute(td::TimeDate) = minute(time(td))
second(td::TimeDate) = second(time(td))
millisecond(td::TimeDate) = millisecond(time(td))
microsecond(td::TimeDate) = microsecond(time(td))
nanosecond(td::TimeDate)  = nanosecond(time(td))

year(tdz::TimeDateZone)   = year(date(tdz))
month(tdz::TimeDateZone)  = month(date(tdz))
day(tdz::TimeDateZone)    = day(date(tdz))
hour(tdz::TimeDateZone)   = hour(time(tdz))
minute(tdz::TimeDateZone) = minute(time(tdz))
second(tdz::TimeDateZone) = second(time(tdz))
millisecond(tdz::TimeDateZone) = millisecond(time(tdz))
microsecond(tdz::TimeDateZone) = microsecond(time(tdz))
nanosecond(tdz::TimeDateZone)  = nanosecond(time(tdz))

